import java.util.Scanner;
abstract class Bank
{
	static final float ROI=7;
	 double cust_bal=200000;
	abstract public void withdraw(int amt);
	abstract public void deposit(int amt);
	abstract public void SI();
	abstract public void display();
}


abstract class Intermediate extends Bank
{
	
	
	
	
	public void deposit(int amt)
	{
		System.out.println("Processing request");
		cust_bal= cust_bal+amt;
		System.out.println("Request processed"+"\n Remaining balance in account:"+cust_bal);
	}
	
	public void SI()
	{
		double si;
		int t=10;
		si= (cust_bal*ROI*t)/100;
		System.out.println("The interest generated by your current balance is:"+si);
	}
	
	abstract public void display();
	abstract public void withdraw(int amt);
}
		
		
class SBI extends Intermediate	
{

		
		public void withdraw(int amt)
	{	
		if(amt>cust_bal)
			System.out.println("Insufficient funds");
		else
		{	
			System.out.println("Processing request");
			if(amt<50000)
				cust_bal=cust_bal-amt;
			else
			{
				cust_bal=(cust_bal-amt-amt*0.01);
				System.out.println("Request processed"+"\n Remaining balance in account:"+cust_bal);
		}
		
		}
	}
		
		public void display()
	{
		System.out.println("The current customer details are:");
		System.out.println("Name:Twisha \n Bank name:SBI");
		System.out.println("Balance in account:"+cust_bal);
	}
		
   }

		
class BOI extends Intermediate	
{

		
		public void withdraw(int amt)
	{	
		if(amt>cust_bal)
			System.out.println("Insufficient funds");
		else
		{	
			System.out.println("Processing request");
			if(amt<50000)
				cust_bal=cust_bal-amt;
			else
			{
				cust_bal=cust_bal-amt-(amt*0.02);
				System.out.println("Request processed"+"\n Remaining balance in account:"+cust_bal);
		}
		
		}
	}
		
		public void display()
	{
		System.out.println("The current customer details are:");
		System.out.println("Name:Twisha \n Bank name:BOI");
		System.out.println("Balance in account:"+cust_bal);
	}
		
  }		
		
		
class AXIS extends Intermediate	
{

		
		public void withdraw(int amt)
	{	
		if(amt>cust_bal)
			System.out.println("Insufficient funds");
		else
		{	
			System.out.println("Processing request");
			if(amt<50000)
				cust_bal=cust_bal-amt;
			else
			{
				cust_bal=cust_bal-amt-amt*0.03;
				System.out.println("Request processed"+"\n Remaining balance in account:"+cust_bal);
		}
		
		}
	}
		
		public void display()
	{
		System.out.println("The current customer details are:");
		System.out.println("Name:Twisha \n Bank name:AXIS");
		System.out.println("Balance in account:"+cust_bal);
	}
		
   }
		


class demo10
{
	public static void main(String args[])
	{
		int option,choice,amt;
		System.out.println("Which bank do you wish to transact with: 1)SBI  2)BOI  3)AXIS");
		System.out.println("Enter your option:");
		Scanner sc= new Scanner(System.in);
		option=sc.nextInt();
		switch(option)
		{
			case 1:
			{
				do
		{
		SBI S=new SBI();
		System.out.println("1. Withdraw \n2.deposit \n 3.display simple interest \n4.Display details \n 5.No pending work");
		System.out.println("Enter what is your option:");
		choice=sc.nextInt();
		switch(choice)
		{
		
					case 1:
                        System.out.println("Enter amount to withdraw");
                        amt=sc.nextInt();
                        S.withdraw(amt);
                        break;
                    case 2:
                        System.out.println("Enter amount to deposit");
                        amt=sc.nextInt();
                        S.deposit(amt);
                        break;
                    case 3:
                    	S.SI();
                    case 4:
                        S.display();
                        break;
                    case 5:
                        System.out.println("Thank you");
                        break;
                    default:
                        System.out.println("Invalid choice");
		}
	}
	while(choice!=5);
	}				


			case 2:
			{
				do
		{
		BOI B=new BOI();
		System.out.println("1. Withdraw \n2.deposit \n 3.display simple interest \n4.Display details \n 5.No pending work");
		System.out.println("Enter what is your option:");
		choice=sc.nextInt();
		switch(choice)
		{
		
					case 1:
                        System.out.println("Enter amount to withdraw");
                        amt=sc.nextInt();
                        B.withdraw(amt);
                        break;
                    case 2:
                        System.out.println("Enter amount to deposit");
                        amt=sc.nextInt();
                        B.deposit(amt);
                        break;
                    case 3:
                    	B.SI();
                    case 4:
                        B.display();
                        break;
                    case 5:
                        System.out.println("Thank you");
                        break;
                    default:
                        System.out.println("Invalid choice");
		}
	}
	while(choice!=5);
	}


			case 3:
			{
				do
		{
		AXIS A=new AXIS();
		System.out.println("1. Withdraw \n2.deposit \n 3.display simple interest \n4.Display details \n 5.No pending work");
		System.out.println("Enter what is your option:");
		choice=sc.nextInt();
		switch(choice)
		{
		
					case 1:
                        System.out.println("Enter amount to withdraw");
                        amt=sc.nextInt();
                        A.withdraw(amt);
                        break;
                    case 2:
                        System.out.println("Enter amount to deposit");
                        amt=sc.nextInt();
                        A.deposit(amt);
                        break;
                    case 3:
                    	A.SI();
                    case 4:
                        A.display();
                        break;
                    case 5:
                        System.out.println("Thank you");
                        break;
                    default:
                        System.out.println("Invalid choice");
		}
	}
	while(choice!=5);
	}
}

System.out.println("All Transaction over");
}
}





















		
		
	
